### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by w4lidz** [w4lidz/gpt4me#4]
How can I solve this?

**Comment by w4lidz** [comment]
You can solve it.

**Comment by w4lidz** [comment]
The problem will be solved.

**Comment by w4lidz** [comment]
Didn't work

**Comment by ShrekBytes** [comment]
> Didn't work

You can make it work.

**Comment by w4lidz** [comment]
> > Didn't work
> 
> You can make it work.

Worked.
